---
- name: Deploy domo
  hosts: irc
  gather_facts: no
  vars_files:
    - vars.yml
  roles:
    - mongodb
  tasks:
    - name: Deploy from git
      remote_user: "{{ service_user }}"
      action: >
        git
        repo="{{ repository_url }}"
        dest="{{ projects_path }}"
        accept_hostkey=True
      notify: restart service

    - name: Install NVM
      remote_user: "{{ service_user }}"
      action: >
        git
        repo="https://github.com/creationix/nvm"
        dest="{{ nvm_path }}"

    - name: Make sure Node.js is installed and properly aliased
      command: >
        bash -c "source {{ nvm_script }} && nvm install {{ nodejs_version }} && nvm alias {{ project_name }} {{ nodejs_version }}"
      register: nvm_result
      changed_when: >
        "already installed" not in nvm_result.stdout
      remote_user: "{{ service_user }}"
      notify: restart service

    - name: Install NPM dependencies and build assets
      command: >
        bash -c "source {{ nvm_script }} && nvm use {{ project_name }} && cd {{ projects_path }} && npm install"
      remote_user: "{{ service_user }}"
      notify: restart service

    - name: Setup Upstart config
      sudo: yes
      remote_user: "{{ service_user }}"
      template: >
        src=templates/upstart.j2
        dest="/etc/init/{{ project_name }}.conf"
        mode=664
      notify: restart service

  handlers:
    - name: restart service
      remote_user: "{{ service_user }}"
      sudo: true
      service: >
        name={{ project_name }}
        state=restarted
